package reducer

import (
	"testing"
	"time"

	"github.com/fulminate-io/logsift"
)

func TestIsGoStackFragment(t *testing.T) {
	tests := []struct {
		name string
		c    logsift.Cluster
		want bool
	}{
		{"register dump", logsift.Cluster{Template: "rax    0xc000123456", Examples: []string{"rax    0xc000123456"}}, true},
		{"go file line", logsift.Cluster{Template: "  /usr/local/go/src/runtime/panic.go:1038", Examples: []string{"  /usr/local/go/src/runtime/panic.go:1038"}}, true},
		{"runtime function", logsift.Cluster{Template: "runtime.gopanic(0xc000123456)", Examples: []string{"runtime.gopanic(0xc000123456)"}}, true},
		{"goroutine header", logsift.Cluster{Template: "goroutine 42 [running]:", Examples: []string{"goroutine 42 [running]:"}}, true},
		{"created by", logsift.Cluster{Template: "created by runtime.init.6", Examples: []string{"created by runtime.init.6"}}, true},
		{"segment register gs", logsift.Cluster{Template: "gs     0x0", Examples: []string{"gs     0x0"}}, true},
		{"flags register", logsift.Cluster{Template: "rflags 0x212", Examples: []string{"rflags 0x212"}}, true},
		{"instruction pointer", logsift.Cluster{Template: "rip    0x40daee", Examples: []string{"rip    0x40daee"}}, true},
		{"assembly file", logsift.Cluster{Template: "  /usr/local/go/src/internal/runtime/syscall/asm_linux_amd64.s:36 +0xe", Examples: []string{"  /usr/local/go/src/internal/runtime/syscall/asm_linux_amd64.s:36 +0xe"}}, true},
		{"net stdlib", logsift.Cluster{Template: "net.(*Dialer).DialContext(0xc00003c7e0, ...)", Examples: []string{"net.(*Dialer).DialContext(0xc00003c7e0, ...)"}}, true},
		{"net/http stdlib", logsift.Cluster{Template: "net/http.(*Transport).dialConn(0xc0000fd380, ...)", Examples: []string{"net/http.(*Transport).dialConn(0xc0000fd380, ...)"}}, true},
		{"syscall call", logsift.Cluster{Template: "syscall.RawSyscall(0xc00049fd48?, ...)", Examples: []string{"syscall.RawSyscall(0xc00049fd48?, ...)"}}, true},
		{"internal/poll", logsift.Cluster{Template: "internal/poll.(*FD).WaitWrite(...)", Examples: []string{"internal/poll.(*FD).WaitWrite(...)"}}, true},
		{"signal info", logsift.Cluster{Template: "PC=0x40daee m=10 sigcode=18446744073709551610", Examples: []string{"PC=0x40daee m=10 sigcode=18446744073709551610"}}, true},
		{"SIGABRT", logsift.Cluster{Template: "SIGABRT: abort", Examples: []string{"SIGABRT: abort"}}, true},
		{"autogenerated", logsift.Cluster{Template: "  <autogenerated>:1 +0x49 fp=0xc0005859c0", Examples: []string{"  <autogenerated>:1 +0x49 fp=0xc0005859c0"}}, true},
		{"github.com call", logsift.Cluster{Template: "github.com/golang/glog.fatalf(...)", Examples: []string{"github.com/golang/glog.fatalf(...)"}}, true},
		{"github.com method", logsift.Cluster{Template: "github.com/golang/glog.(*fileSink).flushDaemon(0x3170118)", Examples: []string{"github.com/golang/glog.(*fileSink).flushDaemon(0x3170118)"}}, true},
		{"main.main", logsift.Cluster{Template: "main.main()", Examples: []string{"main.main()"}}, true},
		{"golang.org call", logsift.Cluster{Template: "golang.org/x/net/http2.(*Transport).dialTLSDefault(0xc00123)", Examples: []string{"golang.org/x/net/http2.(*Transport).dialTLSDefault(0xc00123)"}}, true},
		{"google.golang.org call", logsift.Cluster{Template: "google.golang.org/grpc.(*Server).Serve(0xc000456)", Examples: []string{"google.golang.org/grpc.(*Server).Serve(0xc000456)"}}, true},
		{"internal/runtime/syscall", logsift.Cluster{Template: "internal/runtime/syscall.Syscall6()", Examples: []string{"internal/runtime/syscall.Syscall6()"}}, true},
		{"prefixed with >", logsift.Cluster{Template: "\t>  github.com/go-logr/logr.Logger.Info({})", Examples: []string{"\t>  github.com/go-logr/logr.Logger.Info({})"}}, true},
		{"> space prefix", logsift.Cluster{Template: "> main.main()", Examples: []string{"> main.main()"}}, true},
		// Previously leaking patterns — now caught by universal patterns
		{"k8s.io vendor call", logsift.Cluster{Template: "k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes(0x400038de30, ...)", Examples: []string{"k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes(0x400038de30, ...)"}}, true},
		{"sigs.k8s.io call", logsift.Cluster{Template: "sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc0002fe0c0, 0x0)", Examples: []string{"sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Enabled(0xc0002fe0c0, 0x0)"}}, true},
		{"reflect call", logsift.Cluster{Template: "reflect.(*rtype).MethodByName(0x17f9a40, {0x189ae4f, 0xc})", Examples: []string{"reflect.(*rtype).MethodByName(0x17f9a40, {0x189ae4f, 0xc})"}}, true},
		{"reflect.Value call", logsift.Cluster{Template: "reflect.Value.MethodByName({0x17f9a40?, 0x40004e8000?, 0x400025db58?}, {0x189ae4f?, 0x400025d9f8?})", Examples: []string{"reflect.Value.MethodByName({0x17f9a40?, 0x40004e8000?, 0x400025db58?}, {0x189ae4f?, 0x400025d9f8?})"}}, true},
		{"type:.eq prefix", logsift.Cluster{Template: "type:.eq.k8s.io/apimachinery/pkg/runtime/schema.GroupVersionKind(0x40000af9a8?, 0x40000afae0?)", Examples: []string{"type:.eq.k8s.io/apimachinery/pkg/runtime/schema.GroupVersionKind(0x40000af9a8?, 0x40000afae0?)"}}, true},
		{"cilium vendor > prefix", logsift.Cluster{Template: "\t>  \t/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go:523 +0x24a", Examples: []string{"\t>  \t/go/src/github.com/cilium/cilium/vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go:523 +0x24a"}}, true},
		{"> created by", logsift.Cluster{Template: "\t>  created by sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure in goroutine 1816", Examples: []string{"\t>  created by sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).engageStopProcedure in goroutine 1816"}}, true},
		{"> runtime/debug", logsift.Cluster{Template: "\t>  runtime/debug.Stack()", Examples: []string{"\t>  runtime/debug.Stack()"}}, true},
		{"PC offset only", logsift.Cluster{Template: "  /some/path/file.go:42 +0x1a3", Examples: []string{"  /some/path/file.go:42 +0x1a3"}}, true},
		{"SIGBUS", logsift.Cluster{Template: "SIGBUS: bus error", Examples: []string{"SIGBUS: bus error"}}, true},
		{"normal log", logsift.Cluster{Template: "connection timeout after 3200ms", Examples: []string{"connection timeout after 3200ms"}}, false},
		{"normal error msg", logsift.Cluster{Template: "Error exporting metrics to UAS", Examples: []string{"Error exporting metrics to UAS"}}, false},
		{"normal with parens", logsift.Cluster{Template: "Failed to get pod prod/agent-chat-node-warmer-rz4q6 pods not found", Examples: []string{"Failed to get pod prod/agent-chat-node-warmer-rz4q6 pods not found"}}, false},
		// False positives from infrastructure logs — must NOT match.
		{"k8s audit json", logsift.Cluster{Template: `{"annotations":{"authorization.k8s.io/decision":"allow"},"apiVersion":"audit.k8s.io/v1","auditID":"abc"}`, Examples: []string{`{"annotations":{"authorization.k8s.io/decision":"allow"},"apiVersion":"audit.k8s.io/v1","auditID":"abc"}`}}, false},
		{"postgresql log", logsift.Cluster{Template: "2026-02-27 18:47:01 UTC:10.0.44.136(59262):llama_platform_dbuser@llama_platform_db:[25084]:LOG:  could not receive data from client: Connection reset by peer", Examples: []string{"2026-02-27 18:47:01 UTC:10.0.44.136(59262):llama_platform_dbuser@llama_platform_db:[25084]:LOG:  could not receive data from client: Connection reset by peer"}}, false},
		{"logrus auth line", logsift.Cluster{Template: `time="2026-02-27T18:01:01Z" level=info msg="access granted" arn="arn:aws:iam::927209226484:role/Foo"`, Examples: []string{`time="2026-02-27T18:01:01Z" level=info msg="access granted" arn="arn:aws:iam::927209226484:role/Foo"`}}, false},
		{"rabbitmq warning", logsift.Cluster{Template: `2026-02-27 04:18:36.878494+00:00 [warning] <0.60219548.0> Deprecated features: management_metrics_collection`, Examples: []string{`2026-02-27 04:18:36.878494+00:00 [warning] <0.60219548.0> Deprecated features: management_metrics_collection`}}, false},
		{"lambda report", logsift.Cluster{Template: "REPORT RequestId: e5c92e31 Duration: 91.90 ms Billed Duration: 92 ms", Examples: []string{"REPORT RequestId: e5c92e31 Duration: 91.90 ms Billed Duration: 92 ms"}}, false},
		{"k8s warning log", logsift.Cluster{Template: `W0227 18:04:49.468376      12 dispatcher.go:210] Failed calling webhook, failing open`, Examples: []string{`W0227 18:04:49.468376      12 dispatcher.go:210] Failed calling webhook, failing open`}}, false},
		{"k8s info log", logsift.Cluster{Template: `I0227 18:05:27.012628      11 httplog.go:92] arn:aws:sts::470522838653:assumed-role/foo`, Examples: []string{`I0227 18:05:27.012628      11 httplog.go:92] arn:aws:sts::470522838653:assumed-role/foo`}}, false},
		{"k8s error log", logsift.Cluster{Template: `E0227 18:04:49.468420      12 dispatcher.go:214] "Unhandled Error" err="failed calling webhook"`, Examples: []string{`E0227 18:04:49.468420      12 dispatcher.go:214] "Unhandled Error" err="failed calling webhook"`}}, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isGoStackFragment(&tt.c); got != tt.want {
				t.Errorf("isGoStackFragment() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestGoStackConsolidator(t *testing.T) {
	c := &goStackConsolidator{}
	now := time.Now()

	t.Run("merges many go fragments into single crash cluster", func(t *testing.T) {
		clusters := []logsift.Cluster{
			{Template: "connection timeout", Severity: logsift.SeverityError, Count: 5, FirstSeen: now, LastSeen: now.Add(10 * time.Second)},
			{Template: "goroutine 1 [running]:", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now},
			{Template: "runtime.gopanic(0xc000)", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now.Add(100 * time.Millisecond)},
			{Template: "rax    0xc000123456", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now.Add(200 * time.Millisecond)},
			{Template: "rbx    0x00000000", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now.Add(200 * time.Millisecond)},
			{Template: "  /usr/local/go/src/runtime/panic.go:1038", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now.Add(300 * time.Millisecond)},
			{Template: "created by runtime.init.6", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now.Add(400 * time.Millisecond)},
		}

		result := c.Consolidate(clusters)

		if len(result) != 2 {
			t.Fatalf("expected 2 clusters, got %d", len(result))
		}
		if result[0].Template != "connection timeout" {
			t.Errorf("first cluster should be normal, got %q", result[0].Template)
		}

		crash := result[1]
		if crash.Template != "Go runtime crash (goroutine dump)" {
			t.Errorf("merged template: got %q", crash.Template)
		}
		if crash.Count != 6 {
			t.Errorf("merged count: got %d, want 6", crash.Count)
		}
		if crash.Severity != logsift.SeverityCritical {
			t.Errorf("merged severity: got %s, want %s", crash.Severity, logsift.SeverityCritical)
		}
		if len(crash.Examples) == 0 {
			t.Error("merged crash should have at least 1 example")
		}
	})

	t.Run("fewer than 3 fragments left as-is", func(t *testing.T) {
		clusters := []logsift.Cluster{
			{Template: "normal log", Severity: logsift.SeverityInfo, Count: 10, FirstSeen: now, LastSeen: now},
			{Template: "goroutine 1 [running]:", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now},
			{Template: "runtime.gopanic()", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now},
		}

		result := c.Consolidate(clusters)

		if len(result) != 3 {
			t.Fatalf("expected 3 clusters (no consolidation), got %d", len(result))
		}
	})

	t.Run("temporally separated crashes stay separate", func(t *testing.T) {
		clusters := []logsift.Cluster{
			{Template: "goroutine 1 [running]:", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now},
			{Template: "rax    0xc000123456", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now.Add(100 * time.Millisecond)},
			{Template: "  /usr/local/go/src/runtime/panic.go:1038", Severity: logsift.SeverityError, Count: 1, FirstSeen: now, LastSeen: now.Add(200 * time.Millisecond)},
			{Template: "goroutine 99 [running]:", Severity: logsift.SeverityError, Count: 1, FirstSeen: now.Add(60 * time.Second), LastSeen: now.Add(60 * time.Second)},
			{Template: "rbx    0x00000000", Severity: logsift.SeverityError, Count: 1, FirstSeen: now.Add(60 * time.Second), LastSeen: now.Add(60100 * time.Millisecond)},
			{Template: "created by main.init", Severity: logsift.SeverityError, Count: 1, FirstSeen: now.Add(60 * time.Second), LastSeen: now.Add(60200 * time.Millisecond)},
		}

		result := c.Consolidate(clusters)

		crashCount := 0
		for _, cl := range result {
			if cl.Template == "Go runtime crash (goroutine dump)" {
				crashCount++
			}
		}
		if crashCount != 2 {
			t.Errorf("expected 2 crash clusters, got %d", crashCount)
		}
	})
}
